openshift-kni/debug-tools

- cmd/knit/cmd/cpuaff.go
- cmd/knit/cmd/irqaff.go
- cmd/knit/cmd/root.go
Let's not use global variables if we can help it.
Internal cleanup only, no changes in behaviour.
> knit: avoid global options

- cmd/knit/cmd/cpuaff.go
- cmd/knit/cmd/irqaff.go
- cmd/knit/cmd/root.go
- pkg/procs/info.go
JSON output is easier to parse for machines,
so it's useful to support it alongside custom text output.
> cmd: add JSON output

- cmd/knit/main.go
- pkg/knit/cmd/cpuaff.go
- pkg/knit/cmd/irqaff.go
- pkg/knit/cmd/podres.go
- pkg/knit/cmd/root.go
code movement + trivial rename to move the cobra commands into
a package, to improve reusability.
> knit: move commands into pkg

- pkg/knit/cmd/root.go
- pkg/knit/cmd/wait.go
The `wait` command adds an endless waiting loop.
This allows to use `knit` as entry point of container images,
to make it possible to jump into them and run troubleshooting commands.
> knit: add wait command

- pkg/knit/cmd/root.go
The knit RootCommand wants to own KnitOptions, to avoid globals.
Hence, to make it extensible and allow consumers of the package to
add their subcommands, we need to pass to it the factory functions,
so the new commands can easily consume the KnitOptions.
> cmd: root: allow to pass factory functions

- Makefile
- pkg/irqs/info.go
- pkg/irqs/info_test.go
- pkg/irqs/reporter.go
To support the upcoming `irqwatch` command we need to extract
per-cpu irq counters, and the easiest (but clean and quite reliable) way
is to parse `/proc/interrupts`.
We add helper function and types to represent counters, and to be able
to compute the delta between two counters.
> irqs: add utilities to parse `/proc/interrupts`

- pkg/irqs/info.go
- pkg/irqs/info_test.go
Fix off-by-one error in ReadStats() that lead to incorrect
reporting of IRQ counters.
Add more unittests to cover this function.
> pkg: irqs: fix parsing of /proc/interrupts

- pkg/irqs/info.go
- pkg/knit/cmd/irqwatch.go
- pkg/knit/cmd/root.go
`irqwatch` is meant to help debug/troubleshooting irq pinning scenarios.
We monitor `/proc/interrupts` and we report if a given cpu set handled
IRQs in a given time interval.
With proper IRQ pinning set, the isolated cpus should never handle
IRQs at all; unfortunately, the only way to check this fact is ex-post,
so we need to monitor cpus for long-enough time interval.
> irqwatch command

- test/e2e/knit_irqwatch_test.go
The test will generate a significant amount of random changes in the interrupt counters`
and compare the delta from the irqwatch tool with the expected delta that the test created
Signed-off-by: Talor Itzhak <titzhak@redhat.com>
> E2E test for irqwatch tool

- Makefile
- cmd/cpulist/README.md
- cmd/cpulist/main.go
- pkg/procs/info.go
- test/e2e/cpulist_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/knit_irqaff_test.go
- test/e2e/knit_irqwatch_test.go
- test/e2e/knit_podres_test.go
`cpulist` is meant to be a trivial frontend to the `cpuset` package,
kinda following the old unix tradition of having utilities wrapping syscalls.
Is meant to be used as helper in the validation/test scripts.
See `cmd/cpulist/README.md` for examples.
> add 'cpulist' command

- cmd/knit/main.go
- pkg/knit/cmd/k8s/podres.go
- pkg/knit/cmd/root.go
Since the `podres` pkg pulls in ~32M of deps, bringing
the total executable size to a shopping 40M, push the offending command
in a subpacakge and link it from the client code.
This way, code willing to use the core knit functionality doesn't have
to pay the full price anyway
> pkg: move k8s dependent command in a subpackage

- pkg/knit/cmd/k8s/podres.go
- pkg/knit/cmd/k8s/types.go
proto3 generates the topology info with the int value instead of pointer and
it creates a problem during the json marshal, because it omits field via default
values.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
> podres: does not omit NUMA nodes with id 0 under the topology info

- go.mod
Let's make the go.mod tidier by requiring explicitely
the kube deps. Even if they are going to be replaced anyway,
this should help `go get`.
> go.mod: explicit kube deps

- Dockerfile
- go.mod
- go.sum
This version of pcidb switched the default: now the automatic
fetch of pcidb from the network is opt-in.
> deps: require pcidb 1.0.0

- cmd/knit/main.go
- go.mod
- go.sum
- pkg/knit/cmd/ethtool/ethtool.go
- test/e2e/knit_ethtool_test.go
Add commands to act as simple replacement for `ethtool -l` and `ethtool -k`.
even though very recent linux kernel implemented a new and more capable netlink interface to query the ethernet properties,
we intentionally consume a ioctl-based package because:
1. ioctl capabilities are fine for our use case  (we don't need more modern and powerful features  enabled by netlink just yet)
2. we maximize the backward compatibility
3. netlink-based packages are less mature
> ethtool: add replacement for ethtool -k and -l

- .github/workflows/release.yml
Remove steps pertaining to `kind`, which are useless here,
relics of old copy/paste.
> gh actions: remove useless kind steps

- cmd/knit/main.go
- go.mod
- go.sum
- pkg/knit/cmd/k8s/podinfo.go
- pkg/knit/cmd/k8s/podinfo_test.go
This command will allow us to gather some pod information filtered by
node.
The pod information gathered is filtered with a go-template. Right now
that template is hard-coded but it would be easy to use an incoming
param to read it from a file name if needed in the future.
Pod information is filtered because we want to avoid to show sensible
information in the must-gather tool.
When, if ever, change the output go-template consider:
1.- this output is going to be parsed at must-gather-pao so any change
should be carefully synced
2.- be sure no sensible information is in the final output (like
environmental variables or command parameters that can contain
passwords)
Target for this PR is to create a command to gather the same info as with openshift-kni/performance-addon-operators#906 but …
> Add new `pod-info` command.

- pkg/knit/cmd/k8s/podinfo.go
When some pod has "requests" but not "limits" a comma appears before the
"resource" label making the json wrong formatted.
pod-info command info: #64
> podinfo: Solve error in podinfo template

- pkg/knit/cmd/k8s/podinfo.go
In order to get a kubeconfig to talk to a server API in podinfo command
three elements are tried
- KUBECONFIG env variable
- ~/.kube/config
- in-cluster config
Better to check "in-cluster config" before the one in the user home to
avoid conflicts.
pod-info command info: #64
> podinfo: Try first in-cluster to get kubeconfig

- pkg/pfpstatus/record/recorder.go
- pkg/pfpstatus/record/recorder_test.go
currently this fails to push additional statuses to existing nodes when the capacity of the the recorder is full. Ensure this condition pass for existing nodeRecorders and is only limiting for new nodes.
> pfpstatus: record: fix edge condition
