- OWNERS
- OWNERS_ALIASES
needed to add automatic reviewers courtesy of github
> project: add OWNERS{,_ALIASES}

- README.md
let's start with the goals of this subproject
> doc: bootstrap README

- Dockerfile.tools
- Makefile
add makefile target and build image dockerfile.
> tree: CI integration

- cmd/knit/main.go
- cmd/numalign/main.go
> bump copyright year

- OWNERS_ALIASES
reflect the intended audience of this repo.
> OWNERS: update owners list

- pkg/irqs/soft/info_test.go
Add coverage for the `ReadInfo()` function.
> softirq: add unit test

- pkg/irqs/soft/info_test.go
cover all the functions in the subpkg.
> irqs/soft: complete the test coverage

- go.mod
- go.sum
- test/e2e/e2e_suite_test.go
- test/e2e/knit_irqaff_test.go
The test should be more explicit about why the output is
different from the expected value, and pinpoint the actual
differences with more precision.
> e2e: better diff reporting

- cmd/knit/main.go
- go.mod
- go.sum
- pkg/knit/cmd/ghw/ghw.go
> ghw integration

- .github/workflows/release.yml
Since we release images already, let's also build binaries
automatically.
> gh actions: add action to release binaries

- .github/workflows/release.yml
> gh actions: fix output path

- Dockerfile.tools
- go.mod
> Bump golang 1.17

- .github/workflows/release.yml
> gh actions: bump golang to 1.17

- OWNERS_ALIASES
> update OWNERS 20220421

- Dockerfile.tools
Signed-off-by: Mario Fernandez <mariofer@redhat.com>
> Bump golang 1.18

- .github/workflows/release.yml
> Gh golang 1.18

- Makefile
Signed-off-by: Mario Fernandez <mariofer@redhat.com>
> Delete legacy test entrypoint

- OWNERS_ALIASES
> update aliases 20230109

- OWNERS_ALIASES
> update users 20230110

- OWNERS_ALIASES
> update owners 20230110

- go.mod
- go.sum
- pkg/pfpstatus/command.go
- pkg/pfpstatus/compat.go
- pkg/pfpstatus/pfpstatus.go
- pkg/pfpstatus/pfpstatus_test.go
to be integrated with our fork of scheduler-plugins
> add pfpstatus package

- pkg/machineinformer/relocatablesysfs.go
Based on cadvisor code: https://github.com/google/cadvisor/blob/v0.48.1/utils/sysfs/sysfs.go#L218-L236
> Add RelocatableSysFS IsBlockDeviceHidden

- go.mod
- vendor/modules.txt
this is mostly a relic of past times. Let's clean it up.
> deps: drop unnecessary k/k dep

- .github/workflows/release.yml
- Dockerfile.tools
bump golang builder to 1.23.z
bump github action deps and images to latest
> ghactions: go: bump to latest

- .github/workflows/release.yml
missed a reference to upload-artifacts
> ghactions: bump version

- cmd/ctrreschk/README.md
import abridged version of u/s README for doc purposes.
> doc: ctrreschk: import README
